### PR TITLE
updated readme and fixed for sddm

### PR DESCRIPTION
**Pull request by FrancescoXD**
I made some fixes in the readme

### CODE REVIEW

**Comment by FrancescoXD** [comment]
Now it works with sddm ( issue id #96 )

**Comment by siduck** [comment]
acpi isnt needed btw

**Comment by FrancescoXD** [comment]
> acpi isnt needed btw

I will remove it!

**Comment by siduck** [comment]
and what are these? :thinking: 
image

**Comment by FrancescoXD** [comment]
> and what are these? :thinking: 
> image
> 

Chmod +x at the file

**Pull request merged**
