### PR TITLE
spaces and tabs

### PR DESCRIPTION
**Pull request by erikdubois**
Checking code for spaces and tabs

### CODE REVIEW

**Comment by MinePro120** [comment]
This is something I wanted to do for some time since the indentation of code seems so to be quite inconsistent (I assume because of the patches). Perhaps you could use the tool `indent` (maybe with some arguments) to automatically format all the source files. I would also assume that the config file needs some manual tweaking, especially the comments. Some variables also need to be renamed so they are on the same case (for example, `new_window_attach_on_end` to `newwindowattachonend`) and the code should also be populated with comments so that we know where each patch is located in the code. These could all be separate PRs though.

**Comment by erikdubois** [comment]
To use the `indent` command to apply a universal indentation style to all your files, you can use it with the appropriate options to match your desired coding style. Here's an example of how to use the `indent` command to format a file and some common options you might want to use:

### Basic Usage

```sh
indent filename.c
```

This command will format the file `filename.c` according to the default style.

### Common Options

Here are some common options you might use to customize the formatting:

- **`-kr`**: Use Kernighan & Ritchie style.
- **`-gnu`**: Use GNU style.
- **`-iN`**: Set indentation level to N spaces.
- **`-nut`**: Use spaces instead of tabs.
- **`-tsN`**: Set tab size to N spaces.
- **`-br`**: Put braces on the same line as control statements.

### Example Command

To apply a universal indent style, such as the GNU style with 4-space indentation and no tabs, you would use:

```sh
indent -gnu -i4 -nut -ts4 filename.c
```

### Applying to Multiple Files

To apply this to all your C source files in the current directory, you can use a loop or find command in your shell:

#### Using a Loop

```sh
for file in *.c; do
    indent -gnu -i4 -nut -ts4 "$file"
done
```

#### Using `find`

```sh
find . -name '*.c' -exec indent -gnu -i4 -nut -ts4 {} \;
```

### Creating a Configuration File

If you want to avoid typing the options every time, you can create a configuration file named `.indent.pro` in your home directory or the root of your project:

#### `.indent.pro` Content

```sh
-gnu
-i4
-nut
-ts4
```

#### Usage

Once you have the `.indent.pro` file set up, you can simply run:

```sh
indent filename.c
```

Or to apply it to all C files:

```sh
for file in *.c; do
    indent "$file"
done
```

Or:

```sh
find . -name '*.c' -exec indent {} \;
```

### Summary

By using the `indent` command with appropriate options or a configuration file, you can ensure a consistent indentation style across all your files. The provided examples show how to apply the formatting to individual files or all files in a directory.

**Comment by erikdubois** [comment]
> new_window_attach_on_end

I would prefer keeping the underscores for readability

only 4 references

image

**Comment by erikdubois** [comment]
we can decide on indentation maybe at the end
when we have merge more code into your github
if you are willing to accept more code?

**Comment by erikdubois** [comment]
idea : shall we open up discussions on your github of chadwm to be able to communicate faster/better
image

**Comment by erikdubois** [comment]
maybe this one ?

indent -kr -i4 -ts4 drw.c

**Comment by siduck** [comment]
> idea : shall we open up discussions on your github of chadwm to be able to communicate faster/better image

https://github.com/siduck/chadwm/discussions

**Pull request merged**
