### PR TITLE
Update tag previews patch

### PR DESCRIPTION
**Pull request by MinePro120**
I updated the tag previews patch because of #167 and as it was very outdated. The "scalepreview" option does not change the size of the popup window though (as I think it should), but it rather downscales the preview and tiles it to fit the popup window. This issue is already present though, nothing new. "previewbar" also does not seem to work.

### CODE REVIEW

**Comment by MinePro120** [comment]
Do not push yet. This patch (which I got from [here](https://dwm.suckless.org/patches/tag-previews/)), also does not seem to remove the previews once all windows are closed in a tab. I will open an issue in [explosion-mental/demwm](https://github.com/explosion-mental/demwm).

**Review by siduck — APPROVED** [review]

**Comment by MinePro120** [comment]
@siduck can you reproduce the bugs I mentioned?

**Comment by siduck** [comment]
@MinePro120 been months since i used dwm! i'm on openbox so cant test rn ;((

**Comment by MinePro120** [comment]
Closing until those bugs are fixed.

**Pull request closed without merging**
