### PR TITLE
fixed /bin/dash error

### PR DESCRIPTION
**Pull request by FrancescoXD**

### CODE REVIEW

**Comment by siduck** [comment]
hmm whats the error

**Comment by FrancescoXD** [comment]
`/bin/dash` it's not POSIX and not all have dash shell, in my case I didn't have it. And `~/.dwm/bar/./` gives me error that he cannot find the bar.

**Comment by siduck** [comment]
> `/bin/dash` it's not POSIX and not all have dash shell, in my case I didn't have it. And `~/.dwm/bar/./` gives me error that he cannot find the bar.

dash is a dependency for the bar, it makes the bar very lightweight so I use it , the user can change the shebang if he doesnt want to use dash.

**Comment by siduck** [comment]
> `~/.dwm/bar/./`

image

**Comment by FrancescoXD** [comment]
> dash is a dependency for the bar, it makes the bar very lightweight so I use it , the user can change the shebang if he doesnt want to use dash.

Ok, so it's useful to make it optional and make `/bin/sh` the default shell.

**Comment by FrancescoXD** [comment]
> image
> 

On ssh and zsh it gives error that he cannot find the right path.

**Comment by siduck** [comment]
> > image
> 
> On bash and zsh it gives error that he cannot find the right path.
because dash isnt there on your system I think.

**Comment by FrancescoXD** [comment]
> > > image
> > 
> > On bash and zsh it gives error that he cannot find the right path.
> because dash isnt there on your system I think.

Yeah, I don't have dash, I though it was a mistake, thank you for your time, I'm going to close this pull request.

**Pull request closed without merging**
