### PR TITLE
Add the tokyonight theme

### PR DESCRIPTION
**Pull request by amogusussy**

### CODE REVIEW

**Comment by siduck** [comment]
@amogusussy you should provide it for the eww widget and bar script too!

**Comment by amogusussy** [comment]
Sorry, I forgot about those.

I've just added them now :)

**Comment by amogusussy** [comment]
@siduck Can you merge this PR now?

**Comment by siduck** [comment]
hi @amogusussy , sorry for the delay! I cant test this at the moment, can you show pics of eww and dwmbar?

**Comment by amogusussy** [comment]
I don't actually have eww installed (it isn't in my distro's repos), but comparing it to the other files, it doesn't look like there'd be any issues.

Here's my dwmbar (at the bottom):
https://i.imgur.com/10GCC6Z.png

**Pull request merged**
